# Generated by Django 3.2.4 on 2021-06-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_registereduser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='Journey_cost',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('NOT_SAY', 'I prefer not to say')], max_length=10),
        ),
    ]
