# Generated by Django 3.2.4 on 2021-06-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210622_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='Journey_cost',
        ),
        migrations.AddField(
            model_name='train',
            name='operated_days',
            field=models.CharField(default='All Days', max_length=15),
        ),
        migrations.AddField(
            model_name='train',
            name='ticket_price',
            field=models.IntegerField(default=10),
        ),
    ]
