# Generated by Django 3.2.4 on 2021-06-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210623_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='booked_seats',
            field=models.IntegerField(default=0),
        ),
    ]
