# Generated by Django 3.2.4 on 2021-07-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_train_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=20)),
                ('email', models.CharField(default=None, max_length=25)),
                ('text', models.CharField(default='User Feedback (default)', max_length=1000)),
            ],
        ),
    ]
