# Generated by Django 3.2.4 on 2021-07-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.TextField(choices=[('CONFIRMED', 'confirmed'), ('CANCELLED', 'cancelled')], max_length=10),
        ),
    ]
